package org.nschmidt.abalone.ai;

import static org.nschmidt.abalone.playfield.Field.lookAtField;
import static org.nschmidt.abalone.playfield.Player.BLACK;
import static org.nschmidt.abalone.playfield.Player.EMPTY;
import static org.nschmidt.abalone.playfield.Player.WHITE;

import java.util.HashMap;
import java.util.Map;

import org.nschmidt.abalone.playfield.Field;
import org.nschmidt.abalone.playfield.Player;

public enum HardcodedOpenings {
    INSTANCE;
    
    private static final Map<Field, Field> BLACK_OPENINGS = new HashMap<>();
    private static final Map<Field, Field> WHITE_OPENINGS = new HashMap<>();

    private static void init() {
        BLACK_OPENINGS.clear();
        BLACK_OPENINGS.put(Field.of(new Player[]{WHITE,WHITE,EMPTY,BLACK,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,EMPTY,WHITE,WHITE,EMPTY,BLACK,BLACK,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,BLACK,BLACK,WHITE,WHITE,WHITE,EMPTY,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,EMPTY,EMPTY,WHITE}), Field.of(new Player[]{WHITE,WHITE,EMPTY,EMPTY,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,EMPTY,WHITE,WHITE,BLACK,BLACK,BLACK,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,BLACK,BLACK,WHITE,WHITE,WHITE,EMPTY,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,EMPTY,EMPTY,WHITE}));
        BLACK_OPENINGS.put(Field.of(new Player[]{WHITE,EMPTY,EMPTY,BLACK,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,EMPTY,WHITE,WHITE,WHITE,BLACK,BLACK,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,BLACK,BLACK,EMPTY,WHITE,WHITE,EMPTY,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,EMPTY,WHITE,WHITE}), Field.of(new Player[]{WHITE,EMPTY,EMPTY,BLACK,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,EMPTY,WHITE,WHITE,WHITE,BLACK,BLACK,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,BLACK,BLACK,BLACK,WHITE,WHITE,EMPTY,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,BLACK,EMPTY,EMPTY,WHITE,WHITE}));
        BLACK_OPENINGS.put(Field.of(new Player[]{WHITE,WHITE,EMPTY,EMPTY,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,EMPTY,WHITE,WHITE,BLACK,BLACK,BLACK,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,BLACK,BLACK,WHITE,WHITE,WHITE,EMPTY,EMPTY,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,EMPTY,EMPTY,WHITE}), Field.of(new Player[]{WHITE,WHITE,EMPTY,EMPTY,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,EMPTY,WHITE,WHITE,BLACK,BLACK,BLACK,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,WHITE,EMPTY,EMPTY,EMPTY,BLACK,BLACK,WHITE,BLACK,WHITE,EMPTY,EMPTY,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,BLACK,EMPTY,EMPTY,EMPTY,WHITE}));
        BLACK_OPENINGS.put(Field.of(new Player[]{WHITE,EMPTY,EMPTY,BLACK,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,EMPTY,EMPTY,WHITE,WHITE,WHITE,BLACK,BLACK,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,BLACK,BLACK,BLACK,WHITE,WHITE,EMPTY,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,BLACK,EMPTY,EMPTY,WHITE,WHITE}), Field.of(new Player[]{WHITE,EMPTY,EMPTY,BLACK,EMPTY,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,EMPTY,EMPTY,WHITE,WHITE,BLACK,BLACK,BLACK,EMPTY,EMPTY,EMPTY,EMPTY,WHITE,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,BLACK,BLACK,BLACK,WHITE,WHITE,EMPTY,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,BLACK,EMPTY,EMPTY,WHITE,WHITE}));
        BLACK_OPENINGS.put(Field.of(new Player[]{EMPTY,WHITE,EMPTY,BLACK,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,EMPTY,WHITE,WHITE,EMPTY,BLACK,BLACK,EMPTY,EMPTY,EMPTY,EMPTY,WHITE,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,BLACK,BLACK,EMPTY,WHITE,WHITE,EMPTY,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,EMPTY,WHITE,WHITE}), Field.of(new Player[]{EMPTY,WHITE,EMPTY,BLACK,EMPTY,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,EMPTY,WHITE,WHITE,EMPTY,BLACK,BLACK,EMPTY,EMPTY,EMPTY,EMPTY,WHITE,BLACK,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,BLACK,BLACK,EMPTY,WHITE,WHITE,EMPTY,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,EMPTY,WHITE,WHITE}));
        BLACK_OPENINGS.put(Field.of(new Player[]{WHITE,WHITE,EMPTY,BLACK,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,EMPTY,WHITE,WHITE,EMPTY,BLACK,BLACK,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,WHITE,EMPTY,EMPTY,EMPTY,EMPTY,BLACK,BLACK,EMPTY,WHITE,WHITE,EMPTY,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,EMPTY,WHITE,EMPTY}), Field.of(new Player[]{WHITE,WHITE,EMPTY,BLACK,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,EMPTY,WHITE,WHITE,EMPTY,BLACK,BLACK,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,BLACK,WHITE,EMPTY,EMPTY,EMPTY,EMPTY,BLACK,BLACK,EMPTY,WHITE,WHITE,EMPTY,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,EMPTY,BLACK,EMPTY,WHITE,EMPTY}));
    
        BLACK_OPENINGS.put(Field.of(new Player[]{WHITE,WHITE,EMPTY,BLACK,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,EMPTY,WHITE,WHITE,EMPTY,BLACK,BLACK,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,WHITE,WHITE,EMPTY,EMPTY,EMPTY,BLACK,BLACK,EMPTY,EMPTY,EMPTY,EMPTY,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,EMPTY,WHITE,WHITE}), Field.of(new Player[]{WHITE,WHITE,EMPTY,BLACK,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,EMPTY,WHITE,WHITE,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,BLACK,BLACK,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,WHITE,WHITE,EMPTY,EMPTY,EMPTY,BLACK,BLACK,EMPTY,EMPTY,EMPTY,EMPTY,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,EMPTY,WHITE,WHITE}));
        BLACK_OPENINGS.put(Field.of(new Player[]{WHITE,WHITE,EMPTY,BLACK,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,EMPTY,WHITE,WHITE,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,BLACK,BLACK,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,WHITE,WHITE,EMPTY,EMPTY,EMPTY,BLACK,BLACK,WHITE,WHITE,WHITE,EMPTY,BLACK,BLACK,BLACK,EMPTY,EMPTY,EMPTY,BLACK,BLACK,EMPTY,WHITE,WHITE}), Field.of(new Player[]{WHITE,WHITE,EMPTY,BLACK,BLACK,WHITE,WHITE,WHITE,EMPTY,EMPTY,EMPTY,EMPTY,WHITE,WHITE,BLACK,BLACK,BLACK,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,BLACK,BLACK,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,WHITE,WHITE,EMPTY,EMPTY,EMPTY,BLACK,BLACK,WHITE,WHITE,WHITE,EMPTY,BLACK,BLACK,BLACK,EMPTY,EMPTY,EMPTY,BLACK,BLACK,EMPTY,WHITE,WHITE}));
        BLACK_OPENINGS.put(Field.of(new Player[]{WHITE,WHITE,EMPTY,BLACK,BLACK,WHITE,WHITE,WHITE,EMPTY,EMPTY,EMPTY,EMPTY,WHITE,WHITE,BLACK,BLACK,BLACK,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,BLACK,BLACK,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,WHITE,WHITE,EMPTY,EMPTY,EMPTY,BLACK,BLACK,WHITE,WHITE,WHITE,EMPTY,BLACK,BLACK,BLACK,WHITE,WHITE,EMPTY,BLACK,BLACK,EMPTY,EMPTY,EMPTY}), Field.of(new Player[]{WHITE,WHITE,EMPTY,EMPTY,EMPTY,WHITE,WHITE,WHITE,BLACK,BLACK,EMPTY,EMPTY,WHITE,WHITE,BLACK,BLACK,BLACK,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,BLACK,BLACK,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,WHITE,WHITE,EMPTY,EMPTY,EMPTY,BLACK,BLACK,WHITE,WHITE,WHITE,EMPTY,BLACK,BLACK,BLACK,WHITE,WHITE,EMPTY,BLACK,BLACK,EMPTY,EMPTY,EMPTY}));
    
        BLACK_OPENINGS.put(Field.of(new Player[]{WHITE,WHITE,EMPTY,BLACK,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,EMPTY,EMPTY,EMPTY,EMPTY,BLACK,BLACK,EMPTY,EMPTY,EMPTY,WHITE,WHITE,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,BLACK,BLACK,EMPTY,WHITE,WHITE,EMPTY,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,EMPTY,WHITE,WHITE}), Field.of(new Player[]{WHITE,WHITE,EMPTY,BLACK,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,EMPTY,EMPTY,EMPTY,EMPTY,BLACK,BLACK,EMPTY,EMPTY,EMPTY,WHITE,WHITE,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,BLACK,BLACK,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,WHITE,WHITE,EMPTY,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,EMPTY,WHITE,WHITE}));
        BLACK_OPENINGS.put(Field.of(new Player[]{WHITE,WHITE,EMPTY,BLACK,BLACK,EMPTY,EMPTY,EMPTY,BLACK,BLACK,BLACK,EMPTY,WHITE,WHITE,WHITE,BLACK,BLACK,EMPTY,EMPTY,EMPTY,WHITE,WHITE,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,BLACK,BLACK,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,WHITE,WHITE,EMPTY,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,EMPTY,WHITE,WHITE}), Field.of(new Player[]{WHITE,WHITE,EMPTY,BLACK,BLACK,EMPTY,EMPTY,EMPTY,BLACK,BLACK,BLACK,EMPTY,WHITE,WHITE,WHITE,BLACK,BLACK,EMPTY,EMPTY,EMPTY,WHITE,WHITE,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,BLACK,BLACK,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,BLACK,BLACK,BLACK,WHITE,WHITE,EMPTY,EMPTY,EMPTY,EMPTY,WHITE,WHITE,WHITE,BLACK,BLACK,EMPTY,WHITE,WHITE}));
        BLACK_OPENINGS.put(Field.of(new Player[]{EMPTY,EMPTY,EMPTY,BLACK,BLACK,EMPTY,WHITE,WHITE,BLACK,BLACK,BLACK,EMPTY,WHITE,WHITE,WHITE,BLACK,BLACK,EMPTY,EMPTY,EMPTY,WHITE,WHITE,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,BLACK,BLACK,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,BLACK,BLACK,BLACK,WHITE,WHITE,EMPTY,EMPTY,EMPTY,EMPTY,WHITE,WHITE,WHITE,BLACK,BLACK,EMPTY,WHITE,WHITE}), Field.of(new Player[]{EMPTY,EMPTY,EMPTY,BLACK,BLACK,EMPTY,WHITE,WHITE,BLACK,BLACK,BLACK,EMPTY,WHITE,WHITE,WHITE,BLACK,BLACK,EMPTY,EMPTY,EMPTY,WHITE,WHITE,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,BLACK,BLACK,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,BLACK,BLACK,BLACK,WHITE,WHITE,EMPTY,EMPTY,BLACK,BLACK,WHITE,WHITE,WHITE,EMPTY,EMPTY,EMPTY,WHITE,WHITE}));
    }
    
    /**
     * Ermittelt einen Eröffnungszug für die 61 Felder Variante. <br/>
     * Dies ist notwendig, da die KI nicht selbst die zwei 7er-Gruppen im Standard-Spielfeld effizient und schnell zusammenführen kann. 
     * 
     * @param state das aktuelle Spielfeld
     * @param player der Spieler, welcher an der Reihe ist
     * @return ein Eröffnungszug
     */
    public static Field findOpeningMove(Field state, Player player) {
        if (Field.FIELD_SIZE != 61) {
            return null;
        }
        
        init();
        
        // Erstelle nomalisiertes Feld
        final Player[] currentPieces = new Player[Field.FIELD_SIZE];
        for (int i = 0; i < Field.FIELD_SIZE; i++) {
            currentPieces[i] = lookAtField(state, i);
        }
        
        final Field currentField = Field.of(currentPieces);
        final Field result;
        if (player == WHITE) {
            result = WHITE_OPENINGS.get(currentField);
        } else if (player == BLACK) {
            result = BLACK_OPENINGS.get(currentField);
        } else {
            return null;
        }
        
        return result;
    }
}
